name: Build LaTeX document
on:
  push:
    paths:
      - '**.tex'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: pdflatex main
        uses: dante-ev/latex-action@latest
        with:
          root_file: main.tex
      #   compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
          working_directory: report/
      # - name: bibtex main
      #   uses: dante-ev/latex-action@latest
      #   with:
      #     root_file: main.aux
      #     compiler: bibtex
      #     args: 
      #     working_directory: report/
      # - name: pdflatex main
      #   uses: dante-ev/latex-action@latest
      #   with:
      #     root_file: main.tex
      #     compiler: pdflatex
      #     args: -interaction=nonstopmode -shell-escape
      #     working_directory: report/
      - name: Upload
        uses: actions/upload-artifact@master
        with:
          name: report
          path: report
        if: always()
